//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  route: Route;
  routeConnection: RouteConnection;
  faqItem: FaqItem;
  faqItemConnection: FaqItemConnection;
  sponsor: Sponsor;
  sponsorConnection: SponsorConnection;
  boardMember: BoardMember;
  boardMemberConnection: BoardMemberConnection;
  volunteerGroup: VolunteerGroup;
  volunteerGroupConnection: VolunteerGroupConnection;
  page: Page;
  pageConnection: PageConnection;
  siteSettings: SiteSettings;
  siteSettingsConnection: SiteSettingsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QueryRouteArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryRouteConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RouteFilter>;
};


export type QueryFaqItemArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryFaqItemConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqItemFilter>;
};


export type QuerySponsorArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySponsorConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SponsorFilter>;
};


export type QueryBoardMemberArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryBoardMemberConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BoardMemberFilter>;
};


export type QueryVolunteerGroupArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryVolunteerGroupConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<VolunteerGroupFilter>;
};


export type QueryPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
};


export type QuerySiteSettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  route?: InputMaybe<RouteFilter>;
  faqItem?: InputMaybe<FaqItemFilter>;
  sponsor?: InputMaybe<SponsorFilter>;
  boardMember?: InputMaybe<BoardMemberFilter>;
  volunteerGroup?: InputMaybe<VolunteerGroupFilter>;
  page?: InputMaybe<PageFilter>;
  siteSettings?: InputMaybe<SiteSettingsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Route | FaqItem | Sponsor | BoardMember | VolunteerGroup | Page | SiteSettings | Folder;

export type HomeInfoCards = {
  __typename?: 'HomeInfoCards';
  icon?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  description?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  heroTitle: Scalars['String']['output'];
  heroSubtitle: Scalars['String']['output'];
  heroDescription?: Maybe<Scalars['String']['output']>;
  edition?: Maybe<Scalars['String']['output']>;
  eventDate?: Maybe<Scalars['String']['output']>;
  routeSectionTitle?: Maybe<Scalars['String']['output']>;
  routeSectionSubtitle?: Maybe<Scalars['String']['output']>;
  ctaTitle?: Maybe<Scalars['String']['output']>;
  ctaDescription?: Maybe<Scalars['String']['output']>;
  infoCards?: Maybe<Array<Maybe<HomeInfoCards>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeInfoCardsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  heroTitle?: InputMaybe<StringFilter>;
  heroSubtitle?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  edition?: InputMaybe<StringFilter>;
  eventDate?: InputMaybe<StringFilter>;
  routeSectionTitle?: InputMaybe<StringFilter>;
  routeSectionSubtitle?: InputMaybe<StringFilter>;
  ctaTitle?: InputMaybe<StringFilter>;
  ctaDescription?: InputMaybe<StringFilter>;
  infoCards?: InputMaybe<HomeInfoCardsFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type RouteHighlights = {
  __typename?: 'RouteHighlights';
  text?: Maybe<Scalars['String']['output']>;
};

export type Route = Node & Document & {
  __typename?: 'Route';
  name: Scalars['String']['output'];
  distance: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  startLocation?: Maybe<Scalars['String']['output']>;
  mapEmbedUrl?: Maybe<Scalars['String']['output']>;
  highlights?: Maybe<Array<Maybe<RouteHighlights>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RouteHighlightsFilter = {
  text?: InputMaybe<StringFilter>;
};

export type RouteFilter = {
  name?: InputMaybe<StringFilter>;
  distance?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  startLocation?: InputMaybe<StringFilter>;
  mapEmbedUrl?: InputMaybe<StringFilter>;
  highlights?: InputMaybe<RouteHighlightsFilter>;
};

export type RouteConnectionEdges = {
  __typename?: 'RouteConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Route>;
};

export type RouteConnection = Connection & {
  __typename?: 'RouteConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<RouteConnectionEdges>>>;
};

export type FaqItem = Node & Document & {
  __typename?: 'FaqItem';
  question: Scalars['String']['output'];
  answer: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type FaqItemFilter = {
  question?: InputMaybe<StringFilter>;
  answer?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type FaqItemConnectionEdges = {
  __typename?: 'FaqItemConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<FaqItem>;
};

export type FaqItemConnection = Connection & {
  __typename?: 'FaqItemConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<FaqItemConnectionEdges>>>;
};

export type Sponsor = Node & Document & {
  __typename?: 'Sponsor';
  name: Scalars['String']['output'];
  logo?: Maybe<Scalars['String']['output']>;
  website?: Maybe<Scalars['String']['output']>;
  tier?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type SponsorFilter = {
  name?: InputMaybe<StringFilter>;
  logo?: InputMaybe<ImageFilter>;
  website?: InputMaybe<StringFilter>;
  tier?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type SponsorConnectionEdges = {
  __typename?: 'SponsorConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Sponsor>;
};

export type SponsorConnection = Connection & {
  __typename?: 'SponsorConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SponsorConnectionEdges>>>;
};

export type BoardMember = Node & Document & {
  __typename?: 'BoardMember';
  name: Scalars['String']['output'];
  role: Scalars['String']['output'];
  photo?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type BoardMemberFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  photo?: InputMaybe<ImageFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type BoardMemberConnectionEdges = {
  __typename?: 'BoardMemberConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<BoardMember>;
};

export type BoardMemberConnection = Connection & {
  __typename?: 'BoardMemberConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<BoardMemberConnectionEdges>>>;
};

export type VolunteerGroup = Node & Document & {
  __typename?: 'VolunteerGroup';
  name: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  icon?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type VolunteerGroupFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  icon?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type VolunteerGroupConnectionEdges = {
  __typename?: 'VolunteerGroupConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<VolunteerGroup>;
};

export type VolunteerGroupConnection = Connection & {
  __typename?: 'VolunteerGroupConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<VolunteerGroupConnectionEdges>>>;
};

export type Page = Node & Document & {
  __typename?: 'Page';
  title: Scalars['String']['output'];
  subtitle?: Maybe<Scalars['String']['output']>;
  ctaTitle?: Maybe<Scalars['String']['output']>;
  ctaDescription?: Maybe<Scalars['String']['output']>;
  ctaContactName?: Maybe<Scalars['String']['output']>;
  ctaContactPhone?: Maybe<Scalars['String']['output']>;
  introText?: Maybe<Scalars['String']['output']>;
  aboutText?: Maybe<Scalars['String']['output']>;
  historyText?: Maybe<Scalars['String']['output']>;
  specialMention?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageFilter = {
  title?: InputMaybe<StringFilter>;
  subtitle?: InputMaybe<StringFilter>;
  ctaTitle?: InputMaybe<StringFilter>;
  ctaDescription?: InputMaybe<StringFilter>;
  ctaContactName?: InputMaybe<StringFilter>;
  ctaContactPhone?: InputMaybe<StringFilter>;
  introText?: InputMaybe<StringFilter>;
  aboutText?: InputMaybe<StringFilter>;
  historyText?: InputMaybe<StringFilter>;
  specialMention?: InputMaybe<StringFilter>;
};

export type PageConnectionEdges = {
  __typename?: 'PageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Page>;
};

export type PageConnection = Connection & {
  __typename?: 'PageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PageConnectionEdges>>>;
};

export type SiteSettings = Node & Document & {
  __typename?: 'SiteSettings';
  siteName?: Maybe<Scalars['String']['output']>;
  siteDescription?: Maybe<Scalars['String']['output']>;
  email?: Maybe<Scalars['String']['output']>;
  phone?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  postalCode?: Maybe<Scalars['String']['output']>;
  kvk?: Maybe<Scalars['String']['output']>;
  footerDescription?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSettingsFilter = {
  siteName?: InputMaybe<StringFilter>;
  siteDescription?: InputMaybe<StringFilter>;
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  postalCode?: InputMaybe<StringFilter>;
  kvk?: InputMaybe<StringFilter>;
  footerDescription?: InputMaybe<StringFilter>;
};

export type SiteSettingsConnectionEdges = {
  __typename?: 'SiteSettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteSettings>;
};

export type SiteSettingsConnection = Connection & {
  __typename?: 'SiteSettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteSettingsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updateRoute: Route;
  createRoute: Route;
  updateFaqItem: FaqItem;
  createFaqItem: FaqItem;
  updateSponsor: Sponsor;
  createSponsor: Sponsor;
  updateBoardMember: BoardMember;
  createBoardMember: BoardMember;
  updateVolunteerGroup: VolunteerGroup;
  createVolunteerGroup: VolunteerGroup;
  updatePage: Page;
  createPage: Page;
  updateSiteSettings: SiteSettings;
  createSiteSettings: SiteSettings;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateRouteArgs = {
  relativePath: Scalars['String']['input'];
  params: RouteMutation;
};


export type MutationCreateRouteArgs = {
  relativePath: Scalars['String']['input'];
  params: RouteMutation;
};


export type MutationUpdateFaqItemArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqItemMutation;
};


export type MutationCreateFaqItemArgs = {
  relativePath: Scalars['String']['input'];
  params: FaqItemMutation;
};


export type MutationUpdateSponsorArgs = {
  relativePath: Scalars['String']['input'];
  params: SponsorMutation;
};


export type MutationCreateSponsorArgs = {
  relativePath: Scalars['String']['input'];
  params: SponsorMutation;
};


export type MutationUpdateBoardMemberArgs = {
  relativePath: Scalars['String']['input'];
  params: BoardMemberMutation;
};


export type MutationCreateBoardMemberArgs = {
  relativePath: Scalars['String']['input'];
  params: BoardMemberMutation;
};


export type MutationUpdateVolunteerGroupArgs = {
  relativePath: Scalars['String']['input'];
  params: VolunteerGroupMutation;
};


export type MutationCreateVolunteerGroupArgs = {
  relativePath: Scalars['String']['input'];
  params: VolunteerGroupMutation;
};


export type MutationUpdatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationCreatePageArgs = {
  relativePath: Scalars['String']['input'];
  params: PageMutation;
};


export type MutationUpdateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationCreateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  route?: InputMaybe<RouteMutation>;
  faqItem?: InputMaybe<FaqItemMutation>;
  sponsor?: InputMaybe<SponsorMutation>;
  boardMember?: InputMaybe<BoardMemberMutation>;
  volunteerGroup?: InputMaybe<VolunteerGroupMutation>;
  page?: InputMaybe<PageMutation>;
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  route?: InputMaybe<RouteMutation>;
  faqItem?: InputMaybe<FaqItemMutation>;
  sponsor?: InputMaybe<SponsorMutation>;
  boardMember?: InputMaybe<BoardMemberMutation>;
  volunteerGroup?: InputMaybe<VolunteerGroupMutation>;
  page?: InputMaybe<PageMutation>;
  siteSettings?: InputMaybe<SiteSettingsMutation>;
};

export type HomeInfoCardsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  edition?: InputMaybe<Scalars['String']['input']>;
  eventDate?: InputMaybe<Scalars['String']['input']>;
  routeSectionTitle?: InputMaybe<Scalars['String']['input']>;
  routeSectionSubtitle?: InputMaybe<Scalars['String']['input']>;
  ctaTitle?: InputMaybe<Scalars['String']['input']>;
  ctaDescription?: InputMaybe<Scalars['String']['input']>;
  infoCards?: InputMaybe<Array<InputMaybe<HomeInfoCardsMutation>>>;
};

export type RouteHighlightsMutation = {
  text?: InputMaybe<Scalars['String']['input']>;
};

export type RouteMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  distance?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  startLocation?: InputMaybe<Scalars['String']['input']>;
  mapEmbedUrl?: InputMaybe<Scalars['String']['input']>;
  highlights?: InputMaybe<Array<InputMaybe<RouteHighlightsMutation>>>;
};

export type FaqItemMutation = {
  question?: InputMaybe<Scalars['String']['input']>;
  answer?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type SponsorMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  logo?: InputMaybe<Scalars['String']['input']>;
  website?: InputMaybe<Scalars['String']['input']>;
  tier?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type BoardMemberMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  photo?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type VolunteerGroupMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  icon?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type PageMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  subtitle?: InputMaybe<Scalars['String']['input']>;
  ctaTitle?: InputMaybe<Scalars['String']['input']>;
  ctaDescription?: InputMaybe<Scalars['String']['input']>;
  ctaContactName?: InputMaybe<Scalars['String']['input']>;
  ctaContactPhone?: InputMaybe<Scalars['String']['input']>;
  introText?: InputMaybe<Scalars['String']['input']>;
  aboutText?: InputMaybe<Scalars['String']['input']>;
  historyText?: InputMaybe<Scalars['String']['input']>;
  specialMention?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsMutation = {
  siteName?: InputMaybe<Scalars['String']['input']>;
  siteDescription?: InputMaybe<Scalars['String']['input']>;
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  postalCode?: InputMaybe<Scalars['String']['input']>;
  kvk?: InputMaybe<Scalars['String']['input']>;
  footerDescription?: InputMaybe<Scalars['String']['input']>;
};

export type HomePartsFragment = { __typename: 'Home', heroTitle: string, heroSubtitle: string, heroDescription?: string | null, edition?: string | null, eventDate?: string | null, routeSectionTitle?: string | null, routeSectionSubtitle?: string | null, ctaTitle?: string | null, ctaDescription?: string | null, infoCards?: Array<{ __typename: 'HomeInfoCards', icon?: string | null, title?: string | null, description?: string | null } | null> | null };

export type RoutePartsFragment = { __typename: 'Route', name: string, distance: string, description?: string | null, startLocation?: string | null, mapEmbedUrl?: string | null, highlights?: Array<{ __typename: 'RouteHighlights', text?: string | null } | null> | null };

export type FaqItemPartsFragment = { __typename: 'FaqItem', question: string, answer: string, order?: number | null };

export type SponsorPartsFragment = { __typename: 'Sponsor', name: string, logo?: string | null, website?: string | null, tier?: string | null, order?: number | null };

export type BoardMemberPartsFragment = { __typename: 'BoardMember', name: string, role: string, photo?: string | null, order?: number | null };

export type VolunteerGroupPartsFragment = { __typename: 'VolunteerGroup', name: string, description?: string | null, icon?: string | null, order?: number | null };

export type PagePartsFragment = { __typename: 'Page', title: string, subtitle?: string | null, ctaTitle?: string | null, ctaDescription?: string | null, ctaContactName?: string | null, ctaContactPhone?: string | null, introText?: string | null, aboutText?: string | null, historyText?: string | null, specialMention?: string | null };

export type SiteSettingsPartsFragment = { __typename: 'SiteSettings', siteName?: string | null, siteDescription?: string | null, email?: string | null, phone?: string | null, address?: string | null, postalCode?: string | null, kvk?: string | null, footerDescription?: string | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, heroTitle: string, heroSubtitle: string, heroDescription?: string | null, edition?: string | null, eventDate?: string | null, routeSectionTitle?: string | null, routeSectionSubtitle?: string | null, ctaTitle?: string | null, ctaDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, infoCards?: Array<{ __typename: 'HomeInfoCards', icon?: string | null, title?: string | null, description?: string | null } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, heroTitle: string, heroSubtitle: string, heroDescription?: string | null, edition?: string | null, eventDate?: string | null, routeSectionTitle?: string | null, routeSectionSubtitle?: string | null, ctaTitle?: string | null, ctaDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, infoCards?: Array<{ __typename: 'HomeInfoCards', icon?: string | null, title?: string | null, description?: string | null } | null> | null } | null } | null> | null } };

export type RouteQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type RouteQuery = { __typename?: 'Query', route: { __typename: 'Route', id: string, name: string, distance: string, description?: string | null, startLocation?: string | null, mapEmbedUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, highlights?: Array<{ __typename: 'RouteHighlights', text?: string | null } | null> | null } };

export type RouteConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<RouteFilter>;
}>;


export type RouteConnectionQuery = { __typename?: 'Query', routeConnection: { __typename?: 'RouteConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'RouteConnectionEdges', cursor: string, node?: { __typename: 'Route', id: string, name: string, distance: string, description?: string | null, startLocation?: string | null, mapEmbedUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, highlights?: Array<{ __typename: 'RouteHighlights', text?: string | null } | null> | null } | null } | null> | null } };

export type FaqItemQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type FaqItemQuery = { __typename?: 'Query', faqItem: { __typename: 'FaqItem', id: string, question: string, answer: string, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type FaqItemConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<FaqItemFilter>;
}>;


export type FaqItemConnectionQuery = { __typename?: 'Query', faqItemConnection: { __typename?: 'FaqItemConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'FaqItemConnectionEdges', cursor: string, node?: { __typename: 'FaqItem', id: string, question: string, answer: string, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SponsorQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SponsorQuery = { __typename?: 'Query', sponsor: { __typename: 'Sponsor', id: string, name: string, logo?: string | null, website?: string | null, tier?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SponsorConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SponsorFilter>;
}>;


export type SponsorConnectionQuery = { __typename?: 'Query', sponsorConnection: { __typename?: 'SponsorConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SponsorConnectionEdges', cursor: string, node?: { __typename: 'Sponsor', id: string, name: string, logo?: string | null, website?: string | null, tier?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type BoardMemberQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type BoardMemberQuery = { __typename?: 'Query', boardMember: { __typename: 'BoardMember', id: string, name: string, role: string, photo?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type BoardMemberConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<BoardMemberFilter>;
}>;


export type BoardMemberConnectionQuery = { __typename?: 'Query', boardMemberConnection: { __typename?: 'BoardMemberConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'BoardMemberConnectionEdges', cursor: string, node?: { __typename: 'BoardMember', id: string, name: string, role: string, photo?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type VolunteerGroupQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type VolunteerGroupQuery = { __typename?: 'Query', volunteerGroup: { __typename: 'VolunteerGroup', id: string, name: string, description?: string | null, icon?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type VolunteerGroupConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<VolunteerGroupFilter>;
}>;


export type VolunteerGroupConnectionQuery = { __typename?: 'Query', volunteerGroupConnection: { __typename?: 'VolunteerGroupConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'VolunteerGroupConnectionEdges', cursor: string, node?: { __typename: 'VolunteerGroup', id: string, name: string, description?: string | null, icon?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PageQuery = { __typename?: 'Query', page: { __typename: 'Page', id: string, title: string, subtitle?: string | null, ctaTitle?: string | null, ctaDescription?: string | null, ctaContactName?: string | null, ctaContactPhone?: string | null, introText?: string | null, aboutText?: string | null, historyText?: string | null, specialMention?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PageFilter>;
}>;


export type PageConnectionQuery = { __typename?: 'Query', pageConnection: { __typename?: 'PageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PageConnectionEdges', cursor: string, node?: { __typename: 'Page', id: string, title: string, subtitle?: string | null, ctaTitle?: string | null, ctaDescription?: string | null, ctaContactName?: string | null, ctaContactPhone?: string | null, introText?: string | null, aboutText?: string | null, historyText?: string | null, specialMention?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SiteSettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteSettingsQuery = { __typename?: 'Query', siteSettings: { __typename: 'SiteSettings', id: string, siteName?: string | null, siteDescription?: string | null, email?: string | null, phone?: string | null, address?: string | null, postalCode?: string | null, kvk?: string | null, footerDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SiteSettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
}>;


export type SiteSettingsConnectionQuery = { __typename?: 'Query', siteSettingsConnection: { __typename?: 'SiteSettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteSettingsConnectionEdges', cursor: string, node?: { __typename: 'SiteSettings', id: string, siteName?: string | null, siteDescription?: string | null, email?: string | null, phone?: string | null, address?: string | null, postalCode?: string | null, kvk?: string | null, footerDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  heroTitle
  heroSubtitle
  heroDescription
  edition
  eventDate
  routeSectionTitle
  routeSectionSubtitle
  ctaTitle
  ctaDescription
  infoCards {
    __typename
    icon
    title
    description
  }
}
    `;
export const RoutePartsFragmentDoc = gql`
    fragment RouteParts on Route {
  __typename
  name
  distance
  description
  startLocation
  mapEmbedUrl
  highlights {
    __typename
    text
  }
}
    `;
export const FaqItemPartsFragmentDoc = gql`
    fragment FaqItemParts on FaqItem {
  __typename
  question
  answer
  order
}
    `;
export const SponsorPartsFragmentDoc = gql`
    fragment SponsorParts on Sponsor {
  __typename
  name
  logo
  website
  tier
  order
}
    `;
export const BoardMemberPartsFragmentDoc = gql`
    fragment BoardMemberParts on BoardMember {
  __typename
  name
  role
  photo
  order
}
    `;
export const VolunteerGroupPartsFragmentDoc = gql`
    fragment VolunteerGroupParts on VolunteerGroup {
  __typename
  name
  description
  icon
  order
}
    `;
export const PagePartsFragmentDoc = gql`
    fragment PageParts on Page {
  __typename
  title
  subtitle
  ctaTitle
  ctaDescription
  ctaContactName
  ctaContactPhone
  introText
  aboutText
  historyText
  specialMention
}
    `;
export const SiteSettingsPartsFragmentDoc = gql`
    fragment SiteSettingsParts on SiteSettings {
  __typename
  siteName
  siteDescription
  email
  phone
  address
  postalCode
  kvk
  footerDescription
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const RouteDocument = gql`
    query route($relativePath: String!) {
  route(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...RouteParts
  }
}
    ${RoutePartsFragmentDoc}`;
export const RouteConnectionDocument = gql`
    query routeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: RouteFilter) {
  routeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...RouteParts
      }
    }
  }
}
    ${RoutePartsFragmentDoc}`;
export const FaqItemDocument = gql`
    query faqItem($relativePath: String!) {
  faqItem(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...FaqItemParts
  }
}
    ${FaqItemPartsFragmentDoc}`;
export const FaqItemConnectionDocument = gql`
    query faqItemConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: FaqItemFilter) {
  faqItemConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...FaqItemParts
      }
    }
  }
}
    ${FaqItemPartsFragmentDoc}`;
export const SponsorDocument = gql`
    query sponsor($relativePath: String!) {
  sponsor(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SponsorParts
  }
}
    ${SponsorPartsFragmentDoc}`;
export const SponsorConnectionDocument = gql`
    query sponsorConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SponsorFilter) {
  sponsorConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SponsorParts
      }
    }
  }
}
    ${SponsorPartsFragmentDoc}`;
export const BoardMemberDocument = gql`
    query boardMember($relativePath: String!) {
  boardMember(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...BoardMemberParts
  }
}
    ${BoardMemberPartsFragmentDoc}`;
export const BoardMemberConnectionDocument = gql`
    query boardMemberConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: BoardMemberFilter) {
  boardMemberConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...BoardMemberParts
      }
    }
  }
}
    ${BoardMemberPartsFragmentDoc}`;
export const VolunteerGroupDocument = gql`
    query volunteerGroup($relativePath: String!) {
  volunteerGroup(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...VolunteerGroupParts
  }
}
    ${VolunteerGroupPartsFragmentDoc}`;
export const VolunteerGroupConnectionDocument = gql`
    query volunteerGroupConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: VolunteerGroupFilter) {
  volunteerGroupConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...VolunteerGroupParts
      }
    }
  }
}
    ${VolunteerGroupPartsFragmentDoc}`;
export const PageDocument = gql`
    query page($relativePath: String!) {
  page(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PageParts
  }
}
    ${PagePartsFragmentDoc}`;
export const PageConnectionDocument = gql`
    query pageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PageFilter) {
  pageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PageParts
      }
    }
  }
}
    ${PagePartsFragmentDoc}`;
export const SiteSettingsDocument = gql`
    query siteSettings($relativePath: String!) {
  siteSettings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteSettingsParts
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const SiteSettingsConnectionDocument = gql`
    query siteSettingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteSettingsFilter) {
  siteSettingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteSettingsParts
      }
    }
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    route(variables: RouteQueryVariables, options?: C): Promise<{data: RouteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RouteQueryVariables, query: string}> {
        return requester<{data: RouteQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RouteQueryVariables, query: string}, RouteQueryVariables>(RouteDocument, variables, options);
      },
    routeConnection(variables?: RouteConnectionQueryVariables, options?: C): Promise<{data: RouteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RouteConnectionQueryVariables, query: string}> {
        return requester<{data: RouteConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: RouteConnectionQueryVariables, query: string}, RouteConnectionQueryVariables>(RouteConnectionDocument, variables, options);
      },
    faqItem(variables: FaqItemQueryVariables, options?: C): Promise<{data: FaqItemQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqItemQueryVariables, query: string}> {
        return requester<{data: FaqItemQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqItemQueryVariables, query: string}, FaqItemQueryVariables>(FaqItemDocument, variables, options);
      },
    faqItemConnection(variables?: FaqItemConnectionQueryVariables, options?: C): Promise<{data: FaqItemConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqItemConnectionQueryVariables, query: string}> {
        return requester<{data: FaqItemConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: FaqItemConnectionQueryVariables, query: string}, FaqItemConnectionQueryVariables>(FaqItemConnectionDocument, variables, options);
      },
    sponsor(variables: SponsorQueryVariables, options?: C): Promise<{data: SponsorQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SponsorQueryVariables, query: string}> {
        return requester<{data: SponsorQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SponsorQueryVariables, query: string}, SponsorQueryVariables>(SponsorDocument, variables, options);
      },
    sponsorConnection(variables?: SponsorConnectionQueryVariables, options?: C): Promise<{data: SponsorConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SponsorConnectionQueryVariables, query: string}> {
        return requester<{data: SponsorConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SponsorConnectionQueryVariables, query: string}, SponsorConnectionQueryVariables>(SponsorConnectionDocument, variables, options);
      },
    boardMember(variables: BoardMemberQueryVariables, options?: C): Promise<{data: BoardMemberQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BoardMemberQueryVariables, query: string}> {
        return requester<{data: BoardMemberQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BoardMemberQueryVariables, query: string}, BoardMemberQueryVariables>(BoardMemberDocument, variables, options);
      },
    boardMemberConnection(variables?: BoardMemberConnectionQueryVariables, options?: C): Promise<{data: BoardMemberConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BoardMemberConnectionQueryVariables, query: string}> {
        return requester<{data: BoardMemberConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: BoardMemberConnectionQueryVariables, query: string}, BoardMemberConnectionQueryVariables>(BoardMemberConnectionDocument, variables, options);
      },
    volunteerGroup(variables: VolunteerGroupQueryVariables, options?: C): Promise<{data: VolunteerGroupQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VolunteerGroupQueryVariables, query: string}> {
        return requester<{data: VolunteerGroupQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VolunteerGroupQueryVariables, query: string}, VolunteerGroupQueryVariables>(VolunteerGroupDocument, variables, options);
      },
    volunteerGroupConnection(variables?: VolunteerGroupConnectionQueryVariables, options?: C): Promise<{data: VolunteerGroupConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VolunteerGroupConnectionQueryVariables, query: string}> {
        return requester<{data: VolunteerGroupConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: VolunteerGroupConnectionQueryVariables, query: string}, VolunteerGroupConnectionQueryVariables>(VolunteerGroupConnectionDocument, variables, options);
      },
    page(variables: PageQueryVariables, options?: C): Promise<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}> {
        return requester<{data: PageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageQueryVariables, query: string}, PageQueryVariables>(PageDocument, variables, options);
      },
    pageConnection(variables?: PageConnectionQueryVariables, options?: C): Promise<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}> {
        return requester<{data: PageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PageConnectionQueryVariables, query: string}, PageConnectionQueryVariables>(PageConnectionDocument, variables, options);
      },
    siteSettings(variables: SiteSettingsQueryVariables, options?: C): Promise<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}> {
        return requester<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}, SiteSettingsQueryVariables>(SiteSettingsDocument, variables, options);
      },
    siteSettingsConnection(variables?: SiteSettingsConnectionQueryVariables, options?: C): Promise<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}, SiteSettingsConnectionQueryVariables>(SiteSettingsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.2/content/c09d5a57-e0a3-4c20-a525-74daa3144e73/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  